CREATE DATABASE IF NOT EXISTS chat_memory;
USE chat_memory;

CREATE TABLE IF NOT EXISTS memory (
  id INT AUTO_INCREMENT PRIMARY KEY,
  role VARCHAR(10),
  content TEXT,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
